<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <RootNamespace>Axitor.PointInTime.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Axitor.PointInTime/Axitor.PointInTime.csproj" />
  </ItemGroup>
</Project>