<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <RootNamespace>Axitor.PointInTime.Benchmarks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Axitor.PointInTime/Axitor.PointInTime.csproj" />
  </ItemGroup>
</Project>